---
# This file is located at the path in the `DNSR_CONFIG` environment variable or in the `config.yml` file in the current directory.

# The log configuration.
log:
  # The log level. This can be one of the following: trace, debug, info, warn, error, or off.
  level: debug
  # Enable the udp metrics.
  enable_udp_metrics: true
  # Enable the tcp metrics.
  enable_tcp_metrics: true

keys:
  key1:
    - thibault-cne.fr
  key2:
    - example.com
    - example.org
