---
# This file is located at the path in the `DNSR_CONFIG` environment variable or in the `config.yml` file in the current directory.

# The log configuration.
# This part is optional and every field is optional.
# If not present, the values below are used as defaults.
log:
  # The log level. This can be one of the following: trace, debug, info, warn, error, or off.
  level: debug
  # Enable the metrics.
  enable_metrics: false
  # Enable thread ID in logs.
  enable_thread_id: false
  # Log on stderr.
  stderr: false

keys:
  key1:
    sub.example.fr:
      mname: ns-acme.example.fr.
      rname: postmaster.example.fr.
    example.fr:
      mname: ns-acme.example.fr.
      rname: postmaster.example.fr.
  key2:
    another-example.fr:
      mname: ns-acme.another-example.fr.
      rname: postmaster.another-example.fr.
    fake.another-example.fr:
      mname: ns-acme.another-example.fr.
      rname: postmaster.another-example.fr.
